# Generated by Django 3.2.8 on 2022-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='field_values',
            field=models.ManyToManyField(blank=True, to='service.FieldValue'),
        ),
    ]
