# Generated by Django 3.2.8 on 2022-06-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_field_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='field_values',
            field=models.ManyToManyField(blank=True, related_name='_service_service_field_values_+', to='service.FieldValue'),
        ),
    ]
